CREATE DATABASE AIR
USE AIR
CREATE TABLE CITY
(CNAME VARCHAR(50) NOT NULL,
STATE VARCHAR(15), 
COUNTRY VARCHAR(30),
PRIMARY KEY(CNAME));

CREATE TABLE AIRPORT
(ANAME VARCHAR(50) NOT NULL,
STATE VARCHAR(15), 
COUNTRY VARCHAR(30),
CNAME VARCHAR(50),
PRIMARY KEY(ANAME),
CONSTRAINT A_FK FOREIGN KEY(ANAME) REFERENCES CITY(CNAME) );

CREATE TABLE AIRLINE
(AIRLINEID VARCHAR(3) NOT NULL,
ANAME VARCHAR(50),
PRIMARY KEY(AIRLINEID));

CREATE TABLE CONTAINSS
(AIRLINEID VARCHAR(3) NOT NULL,
ANAME VARCHAR(50) NOT NULL,
PRIMARY KEY(AIRLINEID, ANAME),
FOREIGN KEY(AIRLINEID) REFERENCES AIRLINE(AIRLINEID) ,
FOREIGN KEY(ANAME) REFERENCES AIRPORT(ANAME));

CREATE TABLE SHOP
(SHOP_ID INT NOT NULL ,
SHOP_NAME VARCHAR(50),
OWNER_NAME VARCHAR(20),
PRODUCT VARCHAR(20),
ANAME VARCHAR(50),
PRICE INT,
PRIMARY KEY(SHOP_ID,ANAME),
FOREIGN KEY(ANAME) REFERENCES AIRPORT(ANAME));

CREATE TABLE FLIGHT
(FLIGHT_CODE VARCHAR(10) NOT NULL,
DESTINATION VARCHAR(3),
ARRIVAL VARCHAR(10),
DEPARTURE VARCHAR(10),
STATUS VARCHAR(10),
DURATION VARCHAR(30),
FLIGHT_TYPE VARCHAR(10),
AIRLINEID VARCHAR(3),
PRIMARY KEY(FLIGHT_CODE),
FOREIGN KEY(AIRLINEID) REFERENCES AIRLINE(AIRLINEID) );

CREATE TABLE PASSENGER
(PID INT NOT NULL PRIMARY KEY,
PNAME VARCHAR(20),
ADDRESS VARCHAR(100),
EMAIL_ID VARCHAR(50),
PHONE BIGINT,
AGE INT,
GENDER VARCHAR(1),
);
CREATE TABLE CARRIES
(FLIGHT_CODE VARCHAR(10) NOT NULL,
PID INT NOT NULL,
PRIMARY KEY(FLIGHT_CODE,PID),
FOREIGN KEY(FLIGHT_CODE) REFERENCES FLIGHT(FLIGHT_CODE) ,
FOREIGN KEY(PID) REFERENCES PASSENGER(PID));

CREATE TABLE TICKET
(TICKET_NUMBER INT NOT NULL PRIMARY KEY,
SOURCE VARCHAR(3),
DESTINATION VARCHAR(3),
DATE_OF_BOOKING DATE,
DATE_OF_TRAVEL DATE,
SEATNO VARCHAR(5),
CLASS VARCHAR(15),
DATE_OF_CANCELLATION DATE,
PID INT,
 );

CREATE TABLE BOOKS
(DATE_OF_BOOKING DATE NOT NULL,
SOURCE VARCHAR(3) NOT NULL,
DESTINATION VARCHAR(3) NOT NULL,
CLASS VARCHAR(15) NOT NULL,
PRICE INT,
PID INT NOT NULL,
TICKET_NUMBER INT NOT NULL,
PRIMARY KEY(DATE_OF_BOOKING, SOURCE, DESTINATION, CLASS),
FOREIGN KEY(PID) REFERENCES PASSENGER(PID),
FOREIGN KEY(TICKET_NUMBER) REFERENCES TICKET(TICKET_NUMBER));

CREATE TABLE CANCELS
(DATE_OF_CANCELLATION DATE NOT NULL,
SURCHARGE INT,
PID INT NOT NULL,
TICKET_NUMBER INT NOT NULL
PRIMARY KEY(DATE_OF_CANCELLATION,PID,TICKET_NUMBER),
FOREIGN KEY(PID) REFERENCES PASSENGER(PID),
FOREIGN KEY(TICKET_NUMBER) REFERENCES TICKET(TICKET_NUMBER)
);


CREATE TABLE EMPLOYEE1
(SSN INT NOT NULL,
NAME VARCHAR(20),

ADDRESS VARCHAR(100),
PHONE BIGINT,
AGE INT,
GENDER VARCHAR(1),
SHIFT VARCHAR(20),
ANAME VARCHAR(50),
PRIMARY KEY(SSN),
FOREIGN KEY(ANAME) REFERENCES AIRPORT(ANAME) ON DELETE CASCADE);

CREATE TABLE ADMINISTRATIVE_STAFF
(POSITION VARCHAR(20),
SSN INT NOT NULL,
NAME VARCHAR(20),
ADDRESS VARCHAR(100),
PHONE BIGINT,
AGE INT,
GENDER VARCHAR(1),
SHIFT VARCHAR(20),


PRIMARY KEY(SSN),
FOREIGN KEY(SSN) REFERENCES EMPLOYEE1(SSN)
);

CREATE TABLE TECHNICIAN
(


SSN INT NOT NULL,


ADDRESS VARCHAR(100),
PHONE BIGINT,
AGE INT,
GENDER VARCHAR(1),
SHIFT VARCHAR(20),

PRIMARY KEY(SSN),
FOREIGN KEY(SSN) REFERENCES EMPLOYEE1(SSN));

CREATE TABLE ATC
(

SSN INT NOT NULL,
NAME VARCHAR(20),
ADDRESS VARCHAR(100),
PHONE BIGINT,
AGE INT,
GENDER VARCHAR(1),
SHIFT VARCHAR(20),

PRIMARY KEY(SSN),
FOREIGN KEY(SSN) REFERENCES EMPLOYEE1(SSN));

CREATE TABLE AIRPORT_AUTHORITY
(POSITION VARCHAR(20),
SSN INT NOT NULL,
NAME VARCHAR(20),
ADDRESS VARCHAR(100),
PHONE BIGINT,
AGE INT,
GENDER VARCHAR(1),
SHIFT VARCHAR(20),

PRIMARY KEY(SSN),
FOREIGN KEY(SSN) REFERENCES EMPLOYEE1(SSN));

CREATE TABLE CONTROLS
(SSN INT NOT NULL,
AIRLINEID VARCHAR(3),
PRIMARY KEY(SSN,AIRLINEID),
FOREIGN KEY(AIRLINEID) REFERENCES AIRLINE(AIRLINEID),
FOREIGN KEY(SSN) REFERENCES ATC(SSN));

CREATE TABLE TEST
(SSN INT NOT NULL,
NAME VARCHAR(20),
ADDRESS VARCHAR(100),
PHONE BIGINT,
AGE INT,
GENDER VARCHAR(1),
SHIFT VARCHAR(20),
ANAME VARCHAR(50),
TNAME VARCHAR(20),
TESTNO INT NOT NULL ,
THOURS INT,
TDATE DATE,
AIRLINEID VARCHAR(3),
PRIMARY KEY(SSN,TESTNO,AIRLINEID),
FOREIGN KEY(SSN) REFERENCES TECHNICIAN(SSN),
FOREIGN KEY(AIRLINEID) REFERENCES AIRLINE(AIRLINEID));


CREATE TABLE SERVES1
(SSN INT NOT NULL,
PID INT NOT NULL,
PRIMARY KEY(SSN, PID),
FOREIGN KEY(SSN) REFERENCES EMPLOYEE1(SSN) ,
FOREIGN KEY(PID) REFERENCES PASSENGER(PID) );